plugins {
	id 'org.jetbrains.kotlin.jvm' version '2.3.21'
	id 'org.jetbrains.kotlin.plugin.spring' version '2.3.21'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.vgrente'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springAiVersion', "2.0.1")
}

dependencies {
//	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
	implementation 'tools.jackson.module:jackson-module-kotlin'
//	implementation 'org.springframework.boot:spring-boot-starter-flyway'
//
//	runtimeOnly 'org.postgresql:postgresql'
//
//	developmentOnly 'org.springframework.boot:spring-boot-devtools'
//	testAndDevelopmentOnly 'io.arconia:arconia-dev-services-postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
		mavenBom "io.arconia:arconia-bom:0.30.0"
	}
}

kotlin {
	compilerOptions {
		freeCompilerArgs.addAll '-Xjsr305=strict', '-Xannotation-default-target=param-property'
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
