spring.application.name=ai-chat-with-memory
spring.config.import=optional:file:.env[.properties]

spring.ai.chat.client.enabled=true
spring.ai.google.genai.project-id=${GEMINI_PROJECT_ID}
spring.ai.google.genai.location=europe-west1
spring.ai.google.genai.chat.model=gemini-2.5-flash